"""Pick the newest Watch / Listen / Read items out of data/library.js and write
data/featured.js (window.LL_FEATURED) for the homepage Media section.

The homepage should not load the ~1 MB library, so this keeps a tiny slice.
Run it after build_library.py / build_articles.py:

    python tools/build_featured.py
"""
import json, os, datetime

PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PER_TAB = 5

src = open(os.path.join(PROJ, "data", "library.js"), encoding="utf8").read()
items = json.loads(src[src.index("["):src.rindex("]") + 1])

def label(d):
    dt = datetime.date.fromisoformat(d)
    return f"{dt.strftime('%b')} {dt.day}, {dt.year}"

# YouTube thumbnails keyed by (title, date) so a podcast episode can borrow its
# video twin's artwork.
thumbs = {(x["t"], x["d"]): x["th"] for x in items if x["f"] == "Watch" and x.get("th")}

out = {}
for fmt in ("Watch", "Listen", "Read"):
    picked = []
    for x in sorted((x for x in items if x["f"] == fmt), key=lambda x: x["d"], reverse=True):
        title = x["t"]
        # Weekly shows reuse the series name as the title; add the date so the
        # cards don't read as duplicates.
        if title == x.get("s"):
            title = f"{title} — {label(x['d'])}"
        picked.append({
            "t": title,
            "u": x["u"],
            "s": x.get("s") or fmt,
            "d": label(x["d"]),
            "th": x.get("th") or thumbs.get((x["t"], x["d"])) or "",
        })
        if len(picked) == PER_TAB:
            break
    out[fmt.lower()] = picked

path = os.path.join(PROJ, "data", "featured.js")
with open(path, "w", encoding="utf8", newline="\n") as f:
    f.write("// Generated by tools/build_featured.py from data/library.js. Do not hand-edit.\n")
    f.write("window.LL_FEATURED=" + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")
print("wrote", path, {k: len(v) for k, v in out.items()})
